package pkg;
// Generated by Selenium IDE
import org.junit.Test;

public class Test1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test1() {
    driver.get("https://www.google.com/");
    driver.findElement(By.id("APjFqb")).sendKeys("car");
    driver.findElement(By.cssSelector("center:nth-child(1) > .gNO89b")).click();
  }
}
